---
ci:
  autoupdate_schedule: monthly
  skip:
    - hadolint-docker
    # renovate exceeds tier max size 250MiB on pre-commit.ci
    # (due to huge node.js dependencies)
    - renovate-config-validator

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  # Security linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit
        exclude: tests/

  # Dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker

  # renovate.json validator
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.159.4
    hooks:
      - id: renovate-config-validator
