FROM centos:8

WORKDIR /build

# pyscopg2 requires postgresql-devel
# koji requires krb5-devel
# rpm-py-installer (for koji) requires rpm-devel gcc python3-devel
RUN dnf -y install \
  gcc \
  krb5-devel \
  postgresql-devel \
  python36 \
  python36-devel \
  redhat-rpm-config \
  rpm-devel

RUN pip3 install --no-cache-dir tox

COPY . .

CMD ["tox"]
