---
name: Gating

"on":
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install system dependencies
        uses: nick-invision/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: >-
            sudo apt-get update
            && sudo apt-get install
            libkrb5-dev
            libldap2-dev
            libsasl2-dev

      - name: Test with tox
        run: uvx --with tox-uv tox -e py3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          fail_ci_if_error: true
          verbose: true
          use_oidc: true
          flags: unit-tests

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - Dockerfile

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
